services:
  mysql:
    image: mysql:8
    container_name: resume-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass # ✅ Required
      MYSQL_DATABASE: resume_db # ✅ Optional but useful
      MYSQL_USER: resume_user # ✅ Non-root user
      MYSQL_PASSWORD: resume_pass # ✅ Password for that user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - resume-network

volumes:
  mysql_data:


networks:
  resume-network:
