services:
  postgres:
    image: postgres:15
    container_name: resume-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - resume-network

volumes:
  postgres_data:


networks:
  resume-network:
