version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: resume-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: resume_db
      MYSQL_USER: resume_user
      MYSQL_PASSWORD: resume_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - resume-network

volumes:
  mysql_data:


networks:
  resume-network:
