services:
  db:
    image: postgres:16
    container_name: resume-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resume_user -d resume_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
